---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/4 14:35
---

AudioSourceHolder=class()

function AudioSourceHolder:ctor()
    self.mAudioPath=""
    self.mPlay=false
    self.mAudioSource=nil
end