---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/4 14:35
---

NpcSoundCD=class()

function NpcSoundCD:ctor()
    self.mAudioPath=""
    self.mCD=0
end