---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/7 11:15
---
require("Framework/Model/LoginModel.lua")
require("Framework/Model/RoleManager.lua")
require("Framework/Model/TestModel.lua")
require("Framework/Model/RechargeModel.lua")
require("Framework/Model/MysteryShopModel.lua")
ModelManager=
{
    mModelList={},
}

function ModelManager:Register()
    table.insert(self.mModelList,LoginModel)
    table.insert(self.mModelList,RoleManager)
    table.insert(self.mModelList,TestModel)
    table.insert(self.mModelList,RechargeModel)
    table.insert(self.mModelList,MysteryShopModel)
    for key,value in pairs(self.mModelList) do
        value:Register()
    end
end

function ModelManager:Clear()
    for key,value in pairs(self.mModelList) do
        value:Clear()
    end
end

return ModelManager