---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/18 17:47
---
require("ProtoLua/MysticalStore_pb.lua")
require("Framework/Event/EventDispatch.lua")
require("Framework/Event/EventId.lua")
require("LuaFramework/Debug.lua")

MysteryShopModel=
{
    mGM_MysticalStore_UI_Return = MysticalStore_pb.GM_MysticalStore_UI_Return(),
    mShowRefreshTips=true,
    mMainUIShowIcon = false,
}

function MysteryShopModel:Register()
    EventDispatch:RegisterEventCallback(EventId.MysticalStore_UI_Request,self,self.MysticalStore_UI_Request)
    EventDispatch:RegisterEventCallback(EventId.MysticalStore_Refresh_Request,self,self.MysticalStore_Refresh_Request)
    EventDispatch:RegisterEventCallback(EventId.MysticalStore_Buy_Request,self,self.MysticalStore_Buy_Request)
    EventDispatch:RegisterEventCallback(EventId.MysticalStore_Point_Request,self,self.MysticalStore_Point_Request)
    EventDispatch:RegisterEventCallback(EventId.MysticalStore_Login_Request,self,self.MysticalStore_Login_Request)

    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_UI_RETURN,self,self.GM_MYSTICALSTORE_UI_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_REFRESH_RETURN,self,self.GM_MYSTICALSTORE_REFRESH_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_BUY_RETURN,self,self.GM_MYSTICALSTORE_BUY_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_POINT_RETURN,self,self.GM_MYSTICALSTORE_POINT_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_START_NOTIFY,self,self.GM_MYSTICALSTORE_START_NOTIFY)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_END_NOTIFY,self,self.GM_MYSTICALSTORE_END_NOTIFY)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_MYSTICALSTORE_LONGIN_RETURN,self,self.GM_MYSTICALSTORE_LONGIN_RETURN)
end

--Event回调
--神秘商店请求界面
function MysteryShopModel:MysticalStore_UI_Request()
    ClientManager.GetSingleton().Logic:SendMessageEmpty(GameMessage.GM_MYSTICALSTORE_UI_REQUEST)
end
--神秘商店刷新购买界面
function MysteryShopModel:MysticalStore_Refresh_Request()
    ClientManager.GetSingleton().Logic:SendMessageEmpty(GameMessage.GM_MYSTICALSTORE_REFRESH_REQUEST)
end
--神秘商店请求购买
function MysteryShopModel:MysticalStore_Buy_Request(varData)
    ProtobufStringData.data=varData:SerializeToString()
    ClientManager.GetSingleton().Logic:SendMessageFromLua(GameMessage.GM_MYSTICALSTORE_BUY_REQUEST)
end
--神秘商店请求兑换
function MysteryShopModel:MysticalStore_Point_Request(varData)
    ProtobufStringData.data=varData:SerializeToString()
    ClientManager.GetSingleton().Logic:SendMessageFromLua(GameMessage.GM_MYSTICALSTORE_POINT_REQUEST)
end
--神秘商店请求是否开启
function MysteryShopModel:MysticalStore_Login_Request(varData)
    ClientManager.GetSingleton().Logic:SendMessageEmpty(GameMessage.GM_MYSTICALSTORE_LONGIN_REQUEST)
end

--网络事件回调
--神秘商店界面信息返回
function MysteryShopModel:GM_MYSTICALSTORE_UI_RETURN()
    local tmpMsg=MysticalStore_pb.GM_MysticalStore_UI_Return()
    tmpMsg:ParseFromString(ProtobufStringData.data)
    self.mGM_MysticalStore_UI_Return = tmpMsg

    Debug.Log(" GM_MYSTICALSTORE_UI_RETURN result : " .. tmpMsg.result)
    EventDispatch:DispatchEvent(EventId.MysticalStore_UI_Return)
end
--神秘商店刷新界面返回，通知
function MysteryShopModel:GM_MYSTICALSTORE_REFRESH_RETURN()
    local tmpMsg=MysticalStore_pb.GM_MysticalStore_Refresh_Return()
    tmpMsg:ParseFromString(ProtobufStringData.data)

    if(tmpMsg.result==0) then
        self.mGM_MysticalStore_UI_Return.point = tmpMsg.point
        self.mGM_MysticalStore_UI_Return.buyitems = tmpMsg.buyitems
    else
        WindowManager.GetSingleton():OpenFlyUpFont(Localization.Get("GM_MYSTICALSTORE_REFRESH_RETURN_" .. tmpMsg.result))
    end

    EventDispatch:DispatchEvent(EventId.MysticalStore_Refresh_Return,tmpMsg)
end
--神秘商店购买返回
function MysteryShopModel:GM_MYSTICALSTORE_BUY_RETURN()
    local tmpMsg=MysticalStore_pb.GM_MysticalStore_Buy_Return()
    tmpMsg:ParseFromString(ProtobufStringData.data)

    if(tmpMsg.result == 0) then
        self.mGM_MysticalStore_UI_Return.point = tmpMsg.point

        for key,value in pairs(self.mGM_MysticalStore_UI_Return.buyitems) do
            if(value.gmid==tmpMsg.gmid) then
                self.mGM_MysticalStore_UI_Return.buyitems[key].buystate = tmpMsg.buystate
                break
            end
        end
    else
        WindowManager.GetSingleton():OpenFlyUpFont(Localization.Get("GM_MYSTICALSTORE_BUY_RETURN_" .. tmpMsg.result))
    end
    EventDispatch:DispatchEvent(EventId.MysticalStore_Buy_Return,tmpMsg)
end
--神秘商店积分兑换返回
function MysteryShopModel:GM_MYSTICALSTORE_POINT_RETURN()
    local tmpMsg=MysticalStore_pb.GM_MysticalStore_Point_Return()
    tmpMsg:ParseFromString(ProtobufStringData.data)

    if(tmpMsg.result==0) then
        self.mGM_MysticalStore_UI_Return.point=tmpMsg.point
    else
        WindowManager.GetSingleton():OpenFlyUpFont(Localization.Get("GM_MYSTICALSTORE_POINT_RETURN_" .. tmpMsg.result))
    end

    EventDispatch:DispatchEvent(EventId.MysticalStore_Point_Return,tmpMsg)
end
--通知活动开启
function MysteryShopModel:GM_MYSTICALSTORE_START_NOTIFY()
    self.mGM_MysticalStore_UI_Return.result=1
    EventDispatch:DispatchEvent(EventId.MysticalStore_Start_Notify)
end
--通知活动关闭
function MysteryShopModel:GM_MYSTICALSTORE_END_NOTIFY()
    self.mGM_MysticalStore_UI_Return.result=0
    EventDispatch:DispatchEvent(EventId.MysticalStore_End_Notify)
end

--通知活动是否开启返回
function MysteryShopModel:GM_MYSTICALSTORE_LONGIN_RETURN()
    local tmpMsg=MysticalStore_pb.GM_MysticalStore_Login_Return()
    tmpMsg:ParseFromString(ProtobufStringData.data)
    self.mGM_MysticalStore_UI_Return.result=tmpMsg.result
    EventDispatch:DispatchEvent(EventId.MysticalStore_Login_Return)
end

return MysteryShopModel