require("UI/UI_Recharge/RechargeData.lua")
require("ProtoLua/recharge_pb.lua")
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/11 11:54
---
RechargeModel={}

function RechargeModel:Register()
    --爱心礼包信息
    EventDispatch:RegisterEventCallback(EventId.LoveGifts_Window_Request,self,self.AiXinLiBaoWindowRequest)
    --爱心礼包个人信息
    EventDispatch:RegisterEventCallback(EventId.LoveGifts_Info_Request,self,self.AiXinLiBaoInfoRequest)
    --爱心礼包奖励
    EventDispatch:RegisterEventCallback(EventId.LoveGifts_Get_Request,self,self.AiXinLiBaoGetRequest)

    --爱心礼包信息
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_RECHARGE_LOVEREWARD_RETURN,self,self.AiXinLiBaoWindowReturn)
    --爱心礼包个人信息
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_RECHARGE_LOVEREWARDINFO_RETURN,self,self.AiXinLiBaoInfoReturn)
    --爱心礼包奖励
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_RECHARGE_LOVEREWARDCLICK_RETURN,self,self.AiXinLiBaoGetReturn)
end

--爱心礼包信息
function RechargeModel:AiXinLiBaoWindowRequest()
    ClientManager.GetSingleton().Logic:SendMessageEmptyFromLua(GameMessage.GM_RECHARGE_LOVEREWARD_REQUEST)
end

--爱心礼包信息
function RechargeModel:AiXinLiBaoWindowReturn()
    local tempData=recharge_pb.GM_LoveReward()
    tempData:ParseFromString(ProtobufStringData.data)

    local tempAllDic={}

    if #tempData.m_data > 0 then
        for key,value in pairs(tempData.m_data) do

            --是否有相同档次
            tempBool=false

            --判断是否有相同档次的表
            if #tempAllDic >0 then
                for key2,value2 in pairs(tempAllDic) do
                    if value.m_loverank==value2[1].m_loverank then
                        table.insert(value2,value)
                        tempBool=true
                        break
                    end
                end
            end


            --添加新档次
            if tempBool == false then
                local tempDic={}
                table.insert(tempDic,value)
                table.insert(tempAllDic,tempDic)
            end
        end
    end

    RechargeData.mLoveGiftsAllData = tempAllDic
    EventDispatch:DispatchEvent(EventId.LoveGifts_Window_Return,tempData)
    end

--爱心礼包个人信息
function RechargeModel:AiXinLiBaoInfoRequest()
    ClientManager.GetSingleton().Logic:SendMessageEmptyFromLua(GameMessage.GM_RECHARGE_LOVEREWARDINFO_REQUEST)
end

--爱心礼包个人信息
function RechargeModel:AiXinLiBaoInfoReturn()
    local tempData=recharge_pb.GM_LoveReward_Info()
    tempData:ParseFromString(ProtobufStringData.data)
    RechargeData.mLoveGiftsInfo=tempData
    EventDispatch:DispatchEvent(EventId.LoveGifts_Info_Return,tempData)
end

--爱心礼包获取奖励
function RechargeModel:AiXinLiBaoGetRequest()
    --local tempData=recharge_pb..GM_LoveRewardClick_Requrest()
    --tempData:ParseFromString(ProtobufStringData.data)

    ClientManager.GetSingleton().Logic:SendMessageFromLua(GameMessage.GM_RECHARGE_LOVEREWARDCLICK_REQUEST)
end

--爱心礼包获取奖励
function RechargeModel:AiXinLiBaoGetReturn(varData)
    local tempData=recharge_pb.GM_LoveRewardClick_Return()
    tempData:ParseFromString(ProtobufStringData.data)
    if tempData.result ~= 0 then
        --WindowManager.GetSingleton():OpenFlyUpFont("UIEventListener onClick DownLoad")
        WindowManager.GetSingleton():OpenFlyUpFont(SLuaHelper:GetLocalizationConvert("LoveGifts_GetReturn"..tempData.result))
        --SLuaHelper:GetLocalizationConvert()
    else
        RechargeData.mLoveGiftsInfo.isshow=tempData.isshow
        RechargeData.mLoveGiftsInfo.loverank=tempData.loverank
        RechargeData.mLoveGiftsInfo.lovediamond=tempData.lovediamond
    end
    EventDispatch:DispatchEvent(EventId.LoveGifts_Get_Return,tempData)
end
return RechargeModel
