---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/9/10 15:56
---
require("Framework/Event/EventDispatch.lua")
require("Framework/Event/EventId.lua")
require("Framework/Network/NetMsgDispatch.lua")
require("Framework/Network/GameMessage.lua")
require("ProtoLua/sevenlogin_pb.lua")

TestModel = {
    mRewardData,

    mRewardShowInfo,
    mSureShowData,
    mLoginInfo,
}

function TestModel:Register()
    EventDispatch:RegisterEventCallback(EventId.SevenLogin_RequestRewardData,self,self.SevenLogin_RequestRewardData)
    EventDispatch:RegisterEventCallback(EventId.SevenLogin_RequestInof,self,self.SevenLogin_RequestInof)
    EventDispatch:RegisterEventCallback(EventId.SevenLogin_RequestGetReward,self,self.SevenLogin_RequestGetReward)
    EventDispatch:RegisterEventCallback(EventId.SevenLogin_Show_Request,self,self.SevenLogin_Show_Request)

    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_SEVENDAY_LOGIN_REWARD_RETURN,self,self.GM_SEVENDAY_LOGIN_REWARD_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_SEVENDAY_LOGIN_RETURN,self,self.GM_SEVENDAY_LOGIN_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_SEVENDAY_LOGIN_CLICK_RETURN,self,self.GM_SEVENDAY_LOGIN_CLICK_RETURN)
    NetMsgDispatch:RegisterNetMsgCallback(GameMessage.GM_SEVENDAY_LOGIN_SHOW_RETURN,self,self.GM_SEVENDAY_LOGIN_SHOW_RETURN)
end

--Event回调
--请求七天登录奖励数据
function TestModel:SevenLogin_RequestRewardData()
    ClientManager.GetSingleton().Logic:SendMessageEmpty(GameMessage.GM_SEVENDAY_LOGIN_REWARD_REQUEST)
end
--请求七天登录数据
function TestModel:SevenLogin_RequestInof()
    ClientManager.GetSingleton().Logic:SendMessageEmpty(GameMessage.GM_SEVENDAY_LOGIN_REQUEST)
end
--请求领取七天登录奖励
function TestModel:SevenLogin_RequestGetReward(varData)
    ProtobufStringData.data=varData:SerializeToString()
    ClientManager.GetSingleton().Logic:SendMessageFromLua(GameMessage.GM_SEVENDAY_LOGIN_CLICK_REQUEST)
end
--请求七天登录展示信息
function TestModel:SevenLogin_Show_Request()
    ClientManager.GetSingleton().Logic:SendMessageEmpty(GameMessage.GM_SEVENDAY_LOGIN_SHOW_REQUEST)
end

--NetWork回调
--返回前天登录奖励信息
function TestModel:GM_SEVENDAY_LOGIN_REWARD_RETURN()
    local tmpMsg=sevenlogin_pb.GM_SevenLogin_Data()
    tmpMsg:ParseFromString(ProtobufStringData.data)
    mRewardData = tmpMsg
    EventDispatch:DispatchEvent(EventId.SevenLogin_ReturnRewardData,tmpMsg)
end
--返回七天登录数据
function TestModel:GM_SEVENDAY_LOGIN_RETURN()
    local tmpMsg= sevenlogin_pb.GM_SevenLogin()
    tmpMsg:ParseFromString(ProtobufStringData.data)
    self.mLoginInfo=tmpMsg
    EventDispatch:DispatchEvent(EventId.SevenLogin_ReturnInof,tmpMsg)
end
--返回领取七天登录奖励
function TestModel:GM_SEVENDAY_LOGIN_CLICK_RETURN()
    local tmpMsg=sevenlogin_pb.GM_SevenLogin_Click_Return()
    tmpMsg:ParseFromString(ProtobufStringData.data)
    EventDispatch:DispatchEvent(EventId.SevenLogin_ReturnGetReward,tmpMsg)
end
--返回七天登录展示信息
function TestModel:GM_SEVENDAY_LOGIN_SHOW_RETURN()
    local tmpMsg=sevenlogin_pb.GM_SevenLoginShow_Data()
    tmpMsg:ParseFromString(ProtobufStringData.data)
    self.mRewardShowInfo = tmpMsg
    EventDispatch:DispatchEvent(EventId.SevenLogin_Show_Return,tmpMsg)
end

function TestModel:GetDayVipLv(varLoginDay)
    if(mRewardData==nil) then
        return 0
    end
    for key,value in pairs(mRewardData.m_data) do
        if(value~=nil and value.m_day == varLoginDay) then
            for k,v in pairs(value.m_detail) do
                if(v.m_viplevel>0) then
                    return v.m_viplevel
                end
            end
        end
    end
end

return TestModel